"use client";

import { useLanguage } from "@/context/LanguageContext";

type RuleSection = {
  title: string;
  items: string[];
};

export default function RulesPage() {
  const { language } = useLanguage();

  const copy = {
    EN: {
      title: "Rules",
      subtitle:
        "These rules help keep Wheelio safe, transparent and convenient for buyers and sellers.",
      updated: "Last updated: 29 September 2026",
      introTitle: "General principles",
      intro:
        "By using Wheelio, creating an account, publishing a listing or contacting another user, you agree to follow these rules. Wheelio may remove content, restrict features or suspend accounts that violate them.",
      sections: [
        {
          title: "1. Accounts and identity",
          items: [
            "Provide accurate registration and contact information.",
            "One person should not create multiple accounts to avoid restrictions, bans or payment obligations.",
            "Do not share your password or verification codes with other people.",
            "Phone verification may be required before publishing paid listings or using selected account features.",
            "You are responsible for activity performed through your account until you report unauthorized access.",
          ],
        },
        {
          title: "2. Vehicle listings",
          items: [
            "Listings must describe a real vehicle that the seller is authorized to sell.",
            "Vehicle make, model, year, mileage, price, VIN-related data and other important information must be as accurate as reasonably possible.",
            "Do not intentionally hide major defects, accident damage, legal restrictions, outstanding finance or other information that could materially affect a buyer's decision.",
            "The same vehicle must not be posted repeatedly to manipulate search results.",
            "Listings for stolen vehicles, vehicles with falsified identification, illegal goods or fraudulent offers are prohibited.",
          ],
        },
        {
          title: "3. Photos and media",
          items: [
            "Upload photos of the actual vehicle whenever possible.",
            "Do not use misleading photos, stolen images, unrelated stock images or images that intentionally conceal the vehicle's condition.",
            "Do not upload illegal, offensive or privacy-invasive content.",
            "Wheelio may automatically analyze uploaded photos to classify vehicle views such as front, rear, side, interior, dashboard or VIN plate.",
            "Automatic image classification may be incorrect, so the seller remains responsible for checking and correcting the selected photo category.",
          ],
        },
        {
          title: "4. Price and paid publication",
          items: [
            "The seller is responsible for entering the correct vehicle price.",
            "A publication fee may apply before a listing becomes publicly visible.",
            "A paid listing becomes active only after the payment provider confirms successful payment.",
            "If payment is cancelled, rejected or not confirmed, the listing may remain in draft or pending-payment status.",
            "Publication fees cover the listing service and do not guarantee that the vehicle will be sold.",
            "Refunds, when applicable, are handled according to the payment terms shown during checkout and applicable law.",
          ],
        },
        {
          title: "5. Communication between users",
          items: [
            "Communicate respectfully and only for legitimate vehicle-related purposes.",
            "Spam, harassment, threats, discrimination, scams and attempts to obtain passwords or verification codes are prohibited.",
            "Do not send malicious links, malware or deceptive payment requests.",
            "Never send a verification code received by SMS or phone call to another person.",
            "Wheelio may restrict messaging or accounts where abuse or fraud is suspected.",
          ],
        },
        {
          title: "6. Buying safely",
          items: [
            "Inspect the vehicle and its documents before completing a purchase.",
            "Verify VIN, ownership, registration documents and any available service history.",
            "Do not rely only on information automatically decoded from a VIN or generated by automated tools.",
            "Avoid sending large advance payments to unknown sellers without appropriate verification.",
            "Where appropriate, use a written purchase agreement and keep payment records.",
          ],
        },
        {
          title: "7. Prohibited activity",
          items: [
            "Fraud, impersonation, phishing and identity theft are prohibited.",
            "Manipulating reviews, listings, prices, payment flows or platform functionality is prohibited.",
            "Attempting to bypass security, access another user's data, scrape protected data or interfere with Wheelio infrastructure is prohibited.",
            "Using Wheelio for unlawful transactions, money laundering or other illegal purposes is prohibited.",
            "Automated bulk activity may be restricted unless explicitly authorized by Wheelio.",
          ],
        },
        {
          title: "8. Support and reports",
          items: [
            "Users can contact support through the Help page or the live support widget.",
            "When reporting a problem, provide enough information for the support team to investigate it.",
            "Do not knowingly submit false reports or abuse the support system.",
            "Wheelio may retain support conversations where necessary to resolve disputes, prevent abuse or improve service quality.",
          ],
        },
        {
          title: "9. Automated tools and external services",
          items: [
            "Wheelio may use third-party services for VIN decoding, image analysis, payments, login, SMS and phone verification.",
            "Data returned by external services may be incomplete or inaccurate and should not be treated as an official vehicle inspection.",
            "The seller remains responsible for checking automatically filled vehicle information before publishing.",
            "Availability of third-party services may temporarily affect selected Wheelio features.",
          ],
        },
        {
          title: "10. Moderation and enforcement",
          items: [
            "Wheelio may edit visibility, reject, pause or remove listings that violate these rules or appear fraudulent.",
            "Accounts may be warned, temporarily restricted or suspended depending on the seriousness or repetition of a violation.",
            "Where legally required, Wheelio may cooperate with competent authorities.",
            "Users may contact support if they believe a moderation decision was made in error.",
          ],
        },
        {
          title: "11. Responsibility",
          items: [
            "Wheelio provides a platform that connects buyers and sellers and is not automatically a party to the vehicle sale contract.",
            "Buyers and sellers are responsible for their own negotiations, inspections, agreements, taxes and legal obligations.",
            "Wheelio does not guarantee the condition, ownership, legality or accuracy of every vehicle listing.",
            "Nothing in these rules limits rights that users have under mandatory consumer or other applicable law.",
          ],
        },
        {
          title: "12. Changes to the rules",
          items: [
            "These rules may be updated when Wheelio features, legal requirements or safety practices change.",
            "The current version will be published on this page.",
            "Continued use of the platform after an update means the user is expected to follow the current rules.",
          ],
        },
      ] as RuleSection[],
      footer:
        "If you are unsure whether a listing or action is allowed, contact Wheelio support before proceeding.",
    },

    LT: {
      title: "Taisyklės",
      subtitle:
        "Šios taisyklės padeda išlaikyti Wheelio saugią, skaidrią ir patogią pirkėjams bei pardavėjams.",
      updated: "Paskutinį kartą atnaujinta: 2026 m. rugsėjo 29 d.",
      introTitle: "Bendrieji principai",
      intro:
        "Naudodamiesi Wheelio, kurdami paskyrą, skelbdami skelbimą ar susisiekdami su kitu naudotoju sutinkate laikytis šių taisyklių. Wheelio gali pašalinti turinį, apriboti funkcijas arba sustabdyti paskyras, kurios pažeidžia taisykles.",
      sections: [
        {
          title: "1. Paskyros ir tapatybė",
          items: [
            "Registracijos ir kontaktiniai duomenys turi būti teisingi ir aktualūs.",
            "Negalima kurti kelių paskyrų siekiant apeiti apribojimus, blokavimus ar mokėjimo prievoles.",
            "Nesidalykite slaptažodžiu ar patvirtinimo kodais su kitais asmenimis.",
            "Prieš skelbiant mokamus skelbimus ar naudojant tam tikras funkcijas gali būti reikalaujama patvirtinti telefono numerį.",
            "Naudotojas atsako už veiksmus savo paskyroje tol, kol praneša apie neteisėtą prieigą.",
          ],
        },
        {
          title: "2. Automobilių skelbimai",
          items: [
            "Skelbime turi būti aprašomas realus automobilis, kurį pardavėjas turi teisę parduoti.",
            "Markė, modelis, metai, rida, kaina, su VIN susiję duomenys ir kita svarbi informacija turi būti kiek įmanoma tikslesnė.",
            "Negalima sąmoningai slėpti rimtų defektų, avarijų žalos, teisinių apribojimų, finansinių įsipareigojimų ar kitos pirkėjo sprendimui svarbios informacijos.",
            "Negalima pakartotinai skelbti to paties automobilio siekiant dirbtinai pagerinti jo poziciją paieškoje.",
            "Draudžiami vogtų automobilių, suklastotos tapatybės transporto priemonių, neteisėtų prekių ar apgaulingų pasiūlymų skelbimai.",
          ],
        },
        {
          title: "3. Nuotraukos ir kita medžiaga",
          items: [
            "Kai įmanoma, kelkite tikro parduodamo automobilio nuotraukas.",
            "Negalima naudoti klaidinančių, pavogtų, nesusijusių nuotraukų ar vaizdų, kurie sąmoningai slepia automobilio būklę.",
            "Draudžiamas neteisėtas, įžeidžiantis ar kitų asmenų privatumą pažeidžiantis turinys.",
            "Wheelio gali automatiškai analizuoti nuotraukas ir nustatyti vaizdo tipą: priekį, galą, šoną, saloną, prietaisų skydelį ar VIN lentelę.",
            "Automatinis nuotraukų atpažinimas gali suklysti, todėl pardavėjas privalo patikrinti ir, jei reikia, pataisyti kategoriją.",
          ],
        },
        {
          title: "4. Kaina ir mokamas skelbimo paskelbimas",
          items: [
            "Pardavėjas atsako už teisingai nurodytą automobilio kainą.",
            "Prieš viešai paskelbiant skelbimą gali būti taikomas paskelbimo mokestis.",
            "Mokamas skelbimas tampa aktyvus tik tada, kai mokėjimo paslaugų teikėjas patvirtina sėkmingą mokėjimą.",
            "Jei mokėjimas atšaukiamas, atmetamas ar nepatvirtinamas, skelbimas gali likti juodraščio arba laukiančio mokėjimo būsenoje.",
            "Paskelbimo mokestis mokamas už skelbimo paslaugą ir negarantuoja automobilio pardavimo.",
            "Pinigų grąžinimas, kai jis taikomas, vykdomas pagal atsiskaitymo metu pateiktas sąlygas ir galiojančius teisės aktus.",
          ],
        },
        {
          title: "5. Naudotojų bendravimas",
          items: [
            "Bendraukite pagarbiai ir tik teisėtais su automobiliu susijusiais tikslais.",
            "Draudžiami šlamštas, priekabiavimas, grasinimai, diskriminacija, sukčiavimas ir bandymai išgauti slaptažodžius ar patvirtinimo kodus.",
            "Negalima siųsti kenkėjiškų nuorodų, programų ar klaidinančių mokėjimo prašymų.",
            "Niekada neperduokite kitam asmeniui SMS ar skambučiu gauto patvirtinimo kodo.",
            "Wheelio gali apriboti bendravimo funkcijas ar paskyrą, jei įtariamas piktnaudžiavimas arba sukčiavimas.",
          ],
        },
        {
          title: "6. Saugus automobilio pirkimas",
          items: [
            "Prieš pirkdami apžiūrėkite automobilį ir jo dokumentus.",
            "Patikrinkite VIN, nuosavybės duomenis, registracijos dokumentus ir, jei įmanoma, serviso istoriją.",
            "Nepasikliaukite vien tik automatiškai pagal VIN užpildytais ar kitų automatinių įrankių sugeneruotais duomenimis.",
            "Venkite didelių avansinių mokėjimų nepažįstamiems pardavėjams be tinkamo patikrinimo.",
            "Kai tikslinga, sudarykite rašytinę pirkimo–pardavimo sutartį ir saugokite mokėjimo įrodymus.",
          ],
        },
        {
          title: "7. Draudžiama veikla",
          items: [
            "Draudžiami sukčiavimas, apsimetimas kitu asmeniu, duomenų viliojimas ir tapatybės vagystė.",
            "Draudžiama manipuliuoti skelbimais, kainomis, mokėjimais ar platformos veikimu.",
            "Draudžiama bandyti apeiti saugumo sistemas, pasiekti kitų naudotojų duomenis, rinkti apsaugotus duomenis automatizuotai ar trikdyti Wheelio infrastruktūrą.",
            "Draudžiama naudoti Wheelio neteisėtiems sandoriams, pinigų plovimui ar kitai neteisėtai veiklai.",
            "Masinė automatizuota veikla gali būti ribojama, jei Wheelio jos aiškiai nepatvirtino.",
          ],
        },
        {
          title: "8. Pagalba ir pranešimai",
          items: [
            "Naudotojai gali kreiptis per Pagalbos puslapį arba tiesioginio pokalbio langą.",
            "Pranešdami apie problemą pateikite pakankamai informacijos, kad pagalbos komanda galėtų ją ištirti.",
            "Draudžiama sąmoningai teikti melagingus pranešimus ar piktnaudžiauti pagalbos sistema.",
            "Wheelio gali saugoti pagalbos pokalbius, kai tai būtina ginčams spręsti, piktnaudžiavimui užkirsti ar paslaugų kokybei gerinti.",
          ],
        },
        {
          title: "9. Automatiniai įrankiai ir išorinės paslaugos",
          items: [
            "Wheelio gali naudoti trečiųjų šalių paslaugas VIN dekodavimui, vaizdų analizei, mokėjimams, prisijungimui, SMS ir telefono patvirtinimui.",
            "Išorinių paslaugų pateikti duomenys gali būti neišsamūs ar netikslūs ir nėra oficiali automobilio techninė apžiūra.",
            "Prieš paskelbdamas skelbimą pardavėjas privalo patikrinti automatiškai užpildytą automobilio informaciją.",
            "Trečiųjų šalių paslaugų sutrikimai gali laikinai paveikti kai kurias Wheelio funkcijas.",
          ],
        },
        {
          title: "10. Moderavimas ir taisyklių vykdymas",
          items: [
            "Wheelio gali apriboti matomumą, atmesti, sustabdyti arba pašalinti taisykles pažeidžiančius ar įtartinus skelbimus.",
            "Priklausomai nuo pažeidimo rimtumo ir pasikartojimo paskyrai gali būti skirtas įspėjimas, laikinas apribojimas arba blokavimas.",
            "Kai to reikalauja teisės aktai, Wheelio gali bendradarbiauti su kompetentingomis institucijomis.",
            "Jei naudotojas mano, kad moderavimo sprendimas priimtas klaidingai, jis gali kreiptis į pagalbą.",
          ],
        },
        {
          title: "11. Atsakomybė",
          items: [
            "Wheelio suteikia platformą pirkėjams ir pardavėjams susisiekti ir savaime nėra automobilio pirkimo–pardavimo sutarties šalis.",
            "Pirkėjai ir pardavėjai patys atsako už derybas, automobilio patikrą, sutartis, mokesčius ir kitus teisinius įsipareigojimus.",
            "Wheelio negarantuoja kiekvieno skelbimo automobilio būklės, nuosavybės, teisėtumo ar visų pateiktų duomenų tikslumo.",
            "Šios taisyklės neriboja privalomų naudotojų teisių, kurias suteikia vartotojų apsaugos ar kiti taikomi teisės aktai.",
          ],
        },
        {
          title: "12. Taisyklių pakeitimai",
          items: [
            "Taisyklės gali būti atnaujinamos keičiantis Wheelio funkcijoms, teisės aktams ar saugumo praktikai.",
            "Aktuali taisyklių versija skelbiama šiame puslapyje.",
            "Toliau naudodamasis platforma po taisyklių atnaujinimo naudotojas turi laikytis galiojančios taisyklių versijos.",
          ],
        },
      ] as RuleSection[],
      footer:
        "Jei abejojate, ar konkretus skelbimas ar veiksmas yra leidžiamas, prieš tęsdami kreipkitės į Wheelio pagalbą.",
    },

    RU: {
      title: "Правила",
      subtitle:
        "Эти правила помогают сделать Wheelio безопасной, прозрачной и удобной площадкой для покупателей и продавцов.",
      updated: "Последнее обновление: 29 сентября 2026 г.",
      introTitle: "Общие принципы",
      intro:
        "Используя Wheelio, создавая аккаунт, публикуя объявление или связываясь с другим пользователем, вы соглашаетесь соблюдать эти правила. Wheelio может удалить контент, ограничить функции или приостановить аккаунты, нарушающие правила.",
      sections: [
        {
          title: "1. Аккаунты и личные данные",
          items: [
            "Указывайте корректные и актуальные регистрационные и контактные данные.",
            "Нельзя создавать несколько аккаунтов для обхода ограничений, блокировок или обязательств по оплате.",
            "Не передавайте пароль или коды подтверждения другим людям.",
            "Перед размещением платных объявлений или использованием отдельных функций может потребоваться подтверждение номера телефона.",
            "Пользователь отвечает за действия через свой аккаунт до момента сообщения о несанкционированном доступе.",
          ],
        },
        {
          title: "2. Объявления об автомобилях",
          items: [
            "В объявлении должен быть указан реальный автомобиль, который продавец имеет право продавать.",
            "Марка, модель, год, пробег, цена, VIN-данные и другая важная информация должны быть максимально точными.",
            "Запрещено намеренно скрывать серьёзные дефекты, последствия ДТП, юридические ограничения, финансовые обязательства и другую информацию, существенно влияющую на решение покупателя.",
            "Нельзя многократно публиковать один и тот же автомобиль для искусственного продвижения в поиске.",
            "Запрещены объявления об украденных автомобилях, автомобилях с поддельными идентификаторами, незаконных товарах и мошеннических предложениях.",
          ],
        },
        {
          title: "3. Фотографии и медиа",
          items: [
            "По возможности загружайте фотографии именно продаваемого автомобиля.",
            "Нельзя использовать вводящие в заблуждение, украденные, нерелевантные стоковые фотографии или изображения, скрывающие реальное состояние автомобиля.",
            "Запрещён незаконный, оскорбительный или нарушающий чужую приватность контент.",
            "Wheelio может автоматически анализировать фотографии и определять ракурс: перед, зад, бок, салон, приборная панель или VIN-табличка.",
            "Автоматическая классификация может ошибаться, поэтому продавец обязан проверить и при необходимости исправить категорию фотографии.",
          ],
        },
        {
          title: "4. Цена и платная публикация",
          items: [
            "Продавец несёт ответственность за правильность указанной цены автомобиля.",
            "Перед публичной публикацией объявления может взиматься плата за размещение.",
            "Платное объявление становится активным только после подтверждения успешной оплаты платёжным провайдером.",
            "Если оплата отменена, отклонена или не подтверждена, объявление может остаться черновиком или в статусе ожидания оплаты.",
            "Оплата взимается за услугу публикации и не гарантирует продажу автомобиля.",
            "Возвраты, если они применимы, осуществляются согласно условиям оплаты и обязательному законодательству.",
          ],
        },
        {
          title: "5. Общение пользователей",
          items: [
            "Общайтесь уважительно и только по законным вопросам, связанным с автомобилями.",
            "Запрещены спам, преследование, угрозы, дискриминация, мошенничество и попытки получить чужие пароли или коды подтверждения.",
            "Нельзя отправлять вредоносные ссылки, программы или обманные запросы на оплату.",
            "Никогда не передавайте другому человеку код подтверждения, полученный по SMS или звонку.",
            "Wheelio может ограничить сообщения или аккаунт при подозрении на злоупотребление или мошенничество.",
          ],
        },
        {
          title: "6. Безопасная покупка",
          items: [
            "Перед покупкой осмотрите автомобиль и его документы.",
            "Проверьте VIN, право собственности, регистрационные документы и доступную сервисную историю.",
            "Не полагайтесь только на данные, автоматически полученные по VIN или другими автоматизированными инструментами.",
            "Избегайте крупных авансов неизвестным продавцам без надлежащей проверки.",
            "При необходимости заключайте письменный договор купли-продажи и сохраняйте подтверждения платежей.",
          ],
        },
        {
          title: "7. Запрещённая деятельность",
          items: [
            "Запрещены мошенничество, выдача себя за другого человека, фишинг и кража личности.",
            "Запрещены манипуляции объявлениями, ценами, оплатой или работой платформы.",
            "Запрещены попытки обхода защиты, получения доступа к чужим данным, массового сбора защищённой информации или вмешательства в инфраструктуру Wheelio.",
            "Запрещено использовать Wheelio для незаконных сделок, отмывания денег и другой противоправной деятельности.",
            "Массовая автоматизированная активность может быть ограничена без отдельного разрешения Wheelio.",
          ],
        },
        {
          title: "8. Поддержка и жалобы",
          items: [
            "Связаться с поддержкой можно через страницу «Помощь» или онлайн-чат.",
            "При обращении указывайте достаточно информации, чтобы команда могла разобраться в проблеме.",
            "Запрещено намеренно подавать ложные жалобы или злоупотреблять службой поддержки.",
            "Wheelio может хранить переписку с поддержкой, если это необходимо для разрешения споров, предотвращения злоупотреблений или улучшения качества сервиса.",
          ],
        },
        {
          title: "9. Автоматические инструменты и внешние сервисы",
          items: [
            "Wheelio может использовать сторонние сервисы для VIN-декодирования, анализа изображений, платежей, входа, SMS и телефонного подтверждения.",
            "Данные внешних сервисов могут быть неполными или неточными и не являются официальной технической экспертизой автомобиля.",
            "Перед публикацией продавец обязан проверить автоматически заполненные данные автомобиля.",
            "Недоступность сторонних сервисов может временно влиять на отдельные функции Wheelio.",
          ],
        },
        {
          title: "10. Модерация и меры",
          items: [
            "Wheelio может ограничить видимость, отклонить, приостановить или удалить объявления, нарушающие правила или вызывающие подозрения.",
            "В зависимости от серьёзности и повторяемости нарушения аккаунт может получить предупреждение, временное ограничение или блокировку.",
            "Когда это требуется законом, Wheelio может сотрудничать с компетентными органами.",
            "Если пользователь считает решение модерации ошибочным, он может обратиться в поддержку.",
          ],
        },
        {
          title: "11. Ответственность",
          items: [
            "Wheelio предоставляет площадку для связи покупателей и продавцов и автоматически не становится стороной договора купли-продажи автомобиля.",
            "Покупатели и продавцы самостоятельно отвечают за переговоры, осмотр автомобиля, договоры, налоги и другие юридические обязательства.",
            "Wheelio не гарантирует состояние, право собственности, законность или точность всех данных каждого автомобиля.",
            "Эти правила не ограничивают обязательные права пользователей, предусмотренные законодательством о защите потребителей и иными применимыми нормами.",
          ],
        },
        {
          title: "12. Изменение правил",
          items: [
            "Правила могут обновляться при изменении функций Wheelio, законодательства или практик безопасности.",
            "Актуальная версия публикуется на этой странице.",
            "При дальнейшем использовании платформы после обновления пользователь должен соблюдать действующую версию правил.",
          ],
        },
      ] as RuleSection[],
      footer:
        "Если вы не уверены, разрешено ли конкретное объявление или действие, обратитесь в поддержку Wheelio до его совершения.",
    },
  }[language];

  const shortTitle = (title: string) => title.replace(/^\d+\.\s*/, "");

  return (
    <main className="min-h-screen bg-[#f7f7f5] text-[#111]">
      <section className="relative min-h-[310px] overflow-hidden bg-[#111] text-white md:min-h-[360px]">
        <img src="/images/rules-hero.jpg" alt="" className="absolute inset-0 h-full w-full object-cover object-center" />
        <div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/55 to-black/20" />
        <div className="container relative z-10 flex min-h-[310px] items-center py-10 md:min-h-[360px] md:py-14">
          <div className="max-w-[650px]">
            <div className="mb-5 text-sm font-medium text-white/70">Wheelio&nbsp;&nbsp;/&nbsp;&nbsp;{copy.title}</div>
            <h1 className="text-[42px] font-extrabold leading-[1.02] tracking-[-0.035em] sm:text-5xl md:text-6xl">{copy.title} <span className="text-[#f4b92f]">Wheelio</span></h1>
            <p className="mt-5 max-w-[600px] text-base leading-7 text-white/85 md:text-lg">{copy.subtitle}</p>
            <p className="mt-4 text-xs text-white/55">{copy.updated}</p>
          </div>
        </div>
      </section>

      <div className="container py-7 md:py-10">
        <div className="grid gap-6 lg:grid-cols-[270px_minmax(0,1fr)]">
          <aside className="lg:sticky lg:top-[110px] lg:self-start">
            <div className="rounded-[22px] border border-black/[0.06] bg-white p-2 shadow-[0_10px_35px_rgba(0,0,0,.05)]">
              <a href="#general" className="flex min-h-12 items-center justify-between rounded-2xl bg-[#fff5dd] px-4 text-sm font-bold text-[#151515]">
                <span>{copy.introTitle}</span><span className="text-[#d99f19]">01</span>
              </a>
              <div className="mt-1 hidden lg:block">
                {copy.sections.map((section, index) => (
                  <a key={section.title} href={`#rule-${index + 1}`} className="flex min-h-11 items-center justify-between rounded-xl px-4 text-[13px] font-medium text-black/60 transition hover:bg-black/[0.035] hover:text-black">
                    <span className="truncate pr-3">{shortTitle(section.title)}</span><span className="text-black/30">{String(index + 2).padStart(2, "0")}</span>
                  </a>
                ))}
              </div>
            </div>
          </aside>

          <div className="space-y-4">
            <section id="general" className="scroll-mt-28 overflow-hidden rounded-[24px] border border-black/[0.06] bg-white shadow-[0_10px_35px_rgba(0,0,0,.045)]">
              <div className="grid md:grid-cols-[1fr_240px]">
                <div className="p-6 sm:p-8">
                  <div className="mb-4 flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#fff1cf] text-xs font-extrabold">01</span><h2 className="text-2xl font-extrabold tracking-[-0.02em]">{copy.introTitle}</h2></div>
                  <p className="max-w-3xl text-[15px] leading-7 text-black/65">{copy.intro}</p>
                </div>
                <div className="hidden min-h-[190px] md:block"><img src="/images/rules-hero.jpg" alt="" className="h-full w-full object-cover object-[70%_center]" /></div>
              </div>
            </section>

            {copy.sections.map((section, index) => (
              <section id={`rule-${index + 1}`} key={section.title} className="scroll-mt-28 rounded-[24px] border border-black/[0.06] bg-white p-6 shadow-[0_10px_35px_rgba(0,0,0,.045)] sm:p-8">
                <div className="mb-5 flex items-center gap-3">
                  <span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#fff1cf] text-xs font-extrabold">{String(index + 2).padStart(2, "0")}</span>
                  <h2 className="text-xl font-extrabold tracking-[-0.02em] sm:text-2xl">{shortTitle(section.title)}</h2>
                </div>
                <div className="grid gap-x-8 gap-y-3 md:grid-cols-2">
                  {section.items.map((item) => (
                    <div key={item} className="flex gap-3 rounded-2xl bg-[#fafaf8] p-4 text-[14px] leading-6 text-black/65">
                      <span className="mt-[8px] h-1.5 w-1.5 shrink-0 rounded-full bg-[#e3aa22]" />
                      <span>{item}</span>
                    </div>
                  ))}
                </div>
              </section>
            ))}

            <div className="rounded-[22px] bg-[#111316] p-5 text-sm leading-6 text-white/75 sm:p-6">{copy.footer}</div>
          </div>
        </div>
      </div>
    </main>
  );
}
